# Generated by Django 2.2.6 on 2019-12-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20191210_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=-1234, max_length=16),
            preserve_default=False,
        ),
    ]
