# Generated by Django 2.2.6 on 2019-12-09 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('tree', models.CharField(default='Business', max_length=54)),
                ('name', models.CharField(blank=True, max_length=54, null=True)),
                ('organization', models.CharField(blank=True, max_length=54, null=True)),
                ('member', models.BooleanField(default=False)),
                ('nonprofit', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
