# Generated by Django 2.2.6 on 2019-12-09 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('newproject_text', models.CharField(max_length=512)),
                ('newproject_detail', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('discount_price_nonprofit', models.FloatField(blank=True, null=True)),
                ('discount_price_member', models.FloatField(blank=True, null=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
